name: Static analysis

on: 
  - push
  - pull_request

jobs:
  clippy:
    runs-on: ubuntu-latest
    name: Run clippy
    steps:
      - uses: actions/checkout@v3
      # Replace with below once PR releases: https://github.com/actions-rs/toolchain/pull/209
      # - uses: actions-rs/toolchain@v1
      - uses: oxidecomputer/actions-rs_toolchain@v1
      - uses: Swatinem/rust-cache@v1.3.0
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
  rustfmt:
    runs-on: ubuntu-latest
    name: Check formatter
    steps:
      - uses: actions/checkout@v3
      # Replace with below once PR releases: https://github.com/actions-rs/toolchain/pull/209
      # - uses: actions-rs/toolchain@v1
      - uses: oxidecomputer/actions-rs_toolchain@v1
      - uses: Swatinem/rust-cache@v1.3.0
      - run: cargo fmt --check
