name: Static analysis

on: 
  - push
  - pull_request

jobs:
  clippy:
    runs-on: ubuntu-latest
    name: Run clippy
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
  rustfmt:
    runs-on: ubuntu-latest
    name: Check formatter
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - run: cargo fmt --check
